// <auto-generated />
using System;
using DeckBuilder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeckBuilder.Migrations
{
    [DbContext(typeof(DeckBuilderDbContext))]
    partial class DeckBuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeckBuilder.Domain.Decks.Deck", b =>
                {
                    b.Property<Guid>("IdDeck")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("IdDeck");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("DeckBuilder.Domain.Decks.Deck", b =>
                {
                    b.OwnsMany("DeckBuilder.Domain.Decks.DeckEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("IdDeck")
                                .HasColumnType("uuid");

                            b1.Property<string>("CardScryfallId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Section")
                                .HasColumnType("integer");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("IdDeck", "CardScryfallId", "Section");

                            b1.HasIndex("CardScryfallId");

                            b1.ToTable("DeckEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IdDeck");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
