name: DeckBuilder CI

on:
  push:
    branches: ["main", "master","develop"]
  pull_request:
    branches: ["main", "master","develop"]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        working-directory: ./DeckBuilder
        run: dotnet restore DeckBuilder.csproj

      - name: Check code format (dotnet format)
        working-directory: ./DeckBuilder
        run: dotnet format --verify-no-changes

      - name: Build with analyzers (warnings = errors)
        working-directory: ./DeckBuilder
        run: dotnet build DeckBuilder.csproj --configuration Release

  build-and-test:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        working-directory: ./DeckBuilder
        run: dotnet restore DeckBuilder.csproj

      - name: Build
        working-directory: ./DeckBuilder
        run: dotnet build DeckBuilder.csproj --configuration Release --no-restore

      - name: Test
        working-directory: ./DeckBuilder
        run: |
          if ls *Tests.csproj 1> /dev/null 2>&1; then
            for proj in *Tests.csproj; do
              echo "Running tests for $proj"
              dotnet test "$proj" --configuration Release --no-build
            done
          else
            echo "No test projects found, skipping tests."
          fi

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -f DeckBuilder/Dockerfile \
            -t deckbuilder-api:ci \
            DeckBuilder
